// <auto-generated />
using System;
using DanielAdrianCornejo_Examen1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanielAdrianCornejo_Examen1P.Migrations
{
    [DbContext(typeof(DanielAdrianCornejo_Examen1PContext))]
    [Migration("20241028150410_DC_CambioClase")]
    partial class DC_CambioClase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanielAdrianCornejo_Examen1P.Models.DC_Carro", b =>
                {
                    b.Property<int>("DC_CarroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DC_CarroID"));

                    b.Property<int>("DC_Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("DC_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("DC_Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DC_Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DC_Vendido")
                        .HasColumnType("bit");

                    b.HasKey("DC_CarroID");

                    b.ToTable("DC_Tabla1");
                });
#pragma warning restore 612, 618
        }
    }
}
